from __future__ import annotations
import enum

class FontCollection:
    def __getitem__(self, key: int | str) -> FontFamily: ...

class FontFamily:
    name: str
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> FontVariant: ...

class FontVariant:
    style: Style
    weight: Weight
    filename: str
    def files() -> list[str]: ...

class Style(enum.Enum):
    NORMAL = ...
    ITALIIC = ...
    OBLIQUE = ...

class Weight(enum.Enum): ...
